Repository mkeithX/mkeithx.github.io, pull requests merged in 2024-05, with the labels that each got.

#13 refactor/mid-year-up2024
  README.md
  assets/icons/.gitkeep
  assets/logos/.gitkeep
  examples/README.md
  examples/jupyter-starters/datascience/README.md
  examples/jupyter-starters/datascience/data/US-pumpkins3.csv
  examples/jupyter-starters/datascience/data/grades2.csv
  examples/jupyter-starters/datascience/data/students_data.csv
  examples/jupyter-starters/datascience/data/titanic3.csv
  examples/jupyter-starters/datascience/data/titanic_data.csv
  examples/jupyter-starters/datascience/pumpkin.ipynb
  examples/jupyter-starters/datascience/students.ipynb
  examples/jupyter-starters/datascience/titanic.ipynb
  scripts/.gitkeep
  website/blog/2024/03-01-welcome.mdx
  website/docs/contributing.mdx
  website/docs/media-embeds.mdx
  website/docs/the-keyword.mdx
  website/docusaurus.config.ts
Labels: documentation, enhancement

#15 docs: update for better readability
  website/cosmos/solar-system/index.mdx
  website/cosmos/solar-system/planets/earth.mdx
  website/cosmos/solar-system/planets/jupiter.mdx
  website/cosmos/solar-system/planets/mars.mdx
  website/cosmos/solar-system/planets/mercury.mdx
  website/cosmos/solar-system/planets/neptune.mdx
  website/cosmos/solar-system/planets/planet-x.mdx
  website/cosmos/solar-system/planets/saturn.mdx
  website/cosmos/solar-system/planets/uranus.mdx
  website/cosmos/solar-system/planets/venus.mdx
  website/docs/the-keyword.mdx
Labels: enhancement

#16 mkeithX/update-community-files
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/pull_request_template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  website/docs/contributing.mdx
Labels: PR Internal

#19 This is a test PR
  website/msp/overview.mdx
Labels: enhancement, PR Internal

#21 revamp issue templates
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/pull_request_template.md
Labels: documentation, PR Internal

#22 bumped guides
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  website/docs/guides/git.mdx
Labels: documentation, PR Internal

#23 fix featureRequests
  website/src/css/custom.css
  website/src/plugins/featureRequests/FeatureRequestsPlugin.js
  website/src/plugins/featureRequests/cannyScript.js
  website/src/plugins/featureRequests/styles.module.css
Labels: PR Internal

#26 Code-cleanup
  .prettierignore
  website/blog/2024/05-16-mid-year-upgrades.mdx
  website/docs/_contributing.mdx
  website/docs/_demo-overview.mdx
  website/docs/cheat-sheets/batch.mdx
  website/docs/cheat-sheets/conda.mdx
  website/docs/cheat-sheets/django.mdx
  website/docs/cheat-sheets/git.mdx
  website/docs/cheat-sheets/windows.mdx
  website/docs/guides/_batch-sample.mdx
  website/docs/the-keyword.mdx
  website/docusaurus.config.ts
  website/msp/frequently-used-snippets.mdx
  website/msp/overview.mdx
  website/package-lock.json
  website/package.json
  website/sidebars.ts
  website/sidebarsCommunity.ts
  website/sidebarsMsp.ts
  website/src/css/__test.css
  website/src/css/custom.css
  website/src/pages/examples/_markdownPage.mdx
  website/src/pages/examples/_myComponent.tsx
  website/src/pages/examples/_noIndex.mdx
  website/src/pages/index.module.css
  website/src/pages/index.tsx
  website/src/pages/projects/_data.tsx
  website/static/img/vscode.svg
Labels: documentation, enhancement, PR Internal
