Repository mkeithX/mkeithx.github.io, pull requests merged in 2024-08, with the labels that each got.

#63 feat: web analytics
  website/docusaurus.config.ts
  website/package-lock.json
  website/package.json
Labels: enhancement

#66 test: Verify squash merge behavior
  website/blog/2024/08-03-august-specials.mdx
  website/blog/2024/media/aug-2024-banner copy.png
  website/blog/2024/media/aug-2024-banner.png
  website/docusaurus.config.ts
  website/src/components/QuickStartCards/index.tsx
Labels: PR Internal

#67 chore: Bumped PR template to improved clarity.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement, PR Internal

#71 misc: Update bug report
  .github/ISSUE_TEMPLATE/documentation.yml
Labels: PR Internal, needs triage

#72 chore: refactor and clean up codebase for improved readability
  .github/ISSUE_TEMPLATE/bug.yml
  .github/dependabot.yml
  .github/workflows/deploy.yml
  website/cosmos/astrophysics/about-supernova.mdx
  website/cosmos/astrophysics/fabric-of-space.mdx
  website/cosmos/astrophysics/spacetime-continuum.mdx
  website/cosmos/astrophysics/sun-heliosphere.mdx
  website/cosmos/forces-and-mysteries.mdx
  website/cosmos/index.mdx
  website/cosmos/legacy/cherenkov-radiation.mdx
  website/cosmos/legacy/exploring-principia.mdx
  website/cosmos/legacy/kardashev-scale.mdx
  website/cosmos/legacy/special-general-relativity.mdx
  website/cosmos/legacy/standard-model.mdx
  website/docs/cheat-sheets/windows.mdx
  website/docs/devops/admin-center/mailbox-archive.mdx
  website/docs/devops/index.mdx
  website/docs/keyword.mdx
  website/docusaurus.config.ts
  website/src/components/HomepageFeatures/index.tsx
  website/src/components/HomepageFeatures/styles.module.css
  website/src/components/IntroCards/index.tsx
  website/src/components/IntroCards/styles.module.css
  website/src/css/custom.css
  website/src/pages/index.tsx
  website/src/plugins/featureRequests/FeatureRequestsPage.tsx
  website/static/img/logo/mkxspacehub-logo-alt.png
  website/static/img/rocket-1a.svg
  website/static/img/undraw_code_review.svg
Labels: documentation, enhancement, PR Internal

#73 fix: Actions and WFs
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/dependency-review.yml
  .github/workflows/deploy.yml
Labels: PR Internal

#76 test: Internal PR test
  website/community/kitiplex/m365-guidelines.mdx
Labels: PR Internal

#77 test: actions
  .github/workflows/dependency-review.yml
  .github/workflows/deploy.yml
  package.json
  website/docusaurus.config.ts
Labels: PR Internal

#78 fix: LastUpdate
  .github/workflows/deploy.yml
Labels: bug, dependencies, PR Internal

#79 chore: Upgrade core dependencies
  .github/workflows/deploy.yml
  examples/python-starters/requirements.txt
  scripts/.gitkeep
  website/blog/authors.yml
  website/docs/devops/admin-center/training/install-via-intune.mdx
  website/docs/keyword.mdx
  website/src/components/FeatureBrands/index.tsx
  website/src/components/FeatureBrands/styles.module.css
  website/src/components/HomepageFeatures/index.tsx
  website/src/components/IntroCards/styles.module.css
  website/src/pages/index.tsx
  website/static/CNAME
Labels: enhancement, PR Internal

#80 misc: Update Action for CF Pages Deployment
  .github/workflows/deploy.yml
  .github/workflows/pages-deployment.yaml
Labels: enhancement, PR Internal

#83 misc(blog): Update aug specials
  website/blog/2024/08-19-august-24-specials.mdx
Labels: PR Internal

#88 docs(fix): minor typos
  .github/workflows/pages-deployment.yml
  website/community/kitiplex/team.mdx
  website/docs/custom-deployment/deploy-to-cloudflare-pages.mdx
  website/docs/keyword.mdx
  website/docusaurus.config.ts
  website/sidebars.ts
  website/src/components/TeamProfileCards/index.tsx
Labels: documentation, enhancement, PR Internal

#89 docs: Update and improve core docs.
  .github/workflows/ci.yml
  website/docs/keyword.mdx
  website/docs/website-configuration/index.mdx
  website/docusaurus.config.ts
  website/sidebars.ts
Labels: documentation, enhancement, PR Internal

#90 Refactor: core website structure
  .github/workflows/mkx-ci.yml
  .github/workflows/mkx-deploy.yml
  website/blog/2024/03-01-welcome.mdx
  website/blog/2024/03-17-api-vs-config.mdx
  website/blog/2024/03-17-the-solar-system.mdx
  website/blog/2024/03-20-sitemaps.mdx
  website/blog/2024/03-28-announcing-algolia.mdx
  website/blog/2024/04-10-tribute-to-shiloh.mdx
  website/blog/2024/04-28-the-spacehub.mdx
  website/blog/2024/05-06-python-starters.mdx
  website/blog/2024/05-16-mid-year-upgrades.mdx
  website/blog/2024/05-16-the-may-upgrade.mdx
  website/blog/2024/07-01-devops-july.mdx
  website/blog/2024/07-20-init-py.mdx
  website/blog/2024/_03-01-quality-docs.mdx
  website/blog/2024/_08-03-august-specials.mdx
  website/blog/2024/_08-16-august-specials.mdx
  website/blog/2024/media/aug-2024-banner copy.png
  website/blog/2024/media/aug-2024-banner.png
  website/blog/2024/welcome.mdx
  website/blog/updates/April/index.mdx
  website/blog/updates/August/img/mkx-blog-default.png
  website/blog/updates/August/index.mdx
  website/blog/updates/May/index.mdx
  website/community/__tests__/0-overview.mdx
  website/community/kitiplex/index.mdx
  website/community/kitiplex/team.mdx
  website/docs/_algolia.mdx
  website/docs/_installation.mdx
  website/docs/configs/_configuration.mdx
  website/docs/configs/_content-creation/create-blog.mdx
  website/docs/configs/_content-creation/create-docs.mdx
  website/docs/configs/_content-creation/create-pages.mdx
  website/docs/configs/_custom-deployment/deploy-locally.mdx
  website/docs/configs/_custom-deployment/deploy-to-cloudflare-pages.mdx
  website/docs/configs/_custom-deployment/deploy-to-github-pages.mdx
  website/docs/configs/_deployment.mdx
  website/docs/configs/_plugins-config.mdx
  website/docs/configs/_virtual-environment.mdx
  website/docs/configs/api.mdx
  website/docs/configs/guides/deployment/deploy-cloudflare.mdx
  website/docs/configs/guides/deployment/deploy-github.mdx
  website/docs/configs/guides/docs/blog.mdx
  website/docs/configs/guides/docs/docs-create-doc.mdx
  website/docs/configs/guides/docs/docs-create-page.mdx
  website/docs/configs/index.mdx
  website/docs/devops/admin-center/mailbox-archive.mdx
  website/docs/keyword.mdx
  website/docs/website-configuration/index.mdx
  website/docusaurus.config.ts
  website/package-lock.json
  website/package.json
  website/sidebars.ts
  website/sidebarsCommunity.ts
  website/src/components/TeamProfileCards/index.tsx
  website/src/pages/tests.mdx
Labels: documentation, enhancement

#91 fix: BrokenLinks on Blog
  website/blog/2024/updates/April/index.mdx
  website/blog/2024/updates/August/img/mkx-blog-default.png
  website/blog/2024/updates/August/index.mdx
  website/blog/2024/updates/May/index.mdx
  website/blog/2024/welcome.mdx
  website/blog/img/mkx-blog-default.png
Labels: PR Internal
