Repository mkeithX/mkeithx.github.io, pull requests merged in 2025-05, with the labels that each got.

#393 chore: cleanup-static-assets
  .github/workflows/build-and-deploy.yml
  .github/workflows/python-setup.yml
  website/cosmos/timeline.mdx
  website/docs/how-tos/fix-ms-teams.mdx
  website/docs/how-tos/index.mdx
  website/docs/quick-links.mdx
  website/docs/system-administration/02-cli.mdx
  website/docusaurus.config.ts
  website/sidebars.ts
  website/src/components/FeatureBrands/index.tsx
  website/src/components/FeatureBrands/styles.module.css
  website/src/pages/index.tsx
  website/static/img/astro.svg
  website/static/img/astronaut.svg
  website/static/img/logo/mkx-new-test.png
  website/static/img/rocket-1a.svg
  website/static/img/shuttle.svg
  website/static/img/space/jpl.svg
  website/static/img/troubleshooting/ms-teams-appfolder.png
  website/static/img/troubleshooting/ms-teams-generalsettings.png
  website/static/img/troubleshooting/ms-teams-reset-run.png
  website/static/img/troubleshooting/ms-teams-settings.png
  website/static/img/troubleshooting/ms-teams-win.png
  website/static/img/undraw_bug_fix.svg
  website/static/img/undraw_code_review.svg
  website/static/img/undraw_drone.svg
  website/static/img/undraw_experience.svg
  website/static/img/undraw_experience_design.svg
  website/static/img/undraw_hello.svg
  website/static/img/undraw_progressive.svg
  website/static/img/undraw_react.svg
  website/static/img/undraw_server_down.svg
  website/static/img/undraw_stars.svg
  website/static/img/undraw_taken.svg
  website/static/img/undraw_website.svg
Labels: pr: internal

#396 fix:gtag-configuration
  website/docusaurus.config.ts
Labels: bug, pr: internal

#398 docs: system admin articles
  website/docs/downloads.mdx
  website/docs/system-administration/ms-intune/custom-lockscreen.mdx
  website/docs/system-administration/ms-intune/deploy-win32-app.mdx
  website/docusaurus.config.ts
  website/package-lock.json
Labels: documentation, pr: internal, pr: user story

#399 fix: minor issues in search index
  website/docs/configs/index.mdx
  website/docs/system-administration/ms-intune/custom-lockscreen.mdx
  website/docusaurus.config.ts
Labels: bug, pr: internal

#400 chore: code cleanup
  .github/dependabot.yml
  .github/workflows/build-and-deploy.yml
  .vscode/settings.json
  website/docs/configs/_plugins-config.mdx
  website/docs/configs/_virtual-environment.mdx
  website/docs/introduction.mdx
  website/docs/learn.mdx
  website/docs/learn/react-live-demo.mdx
  website/docs/speedtest.mdx
  website/docs/system-administration/ms-entra/create-dynamic-group.mdx
  website/docs/system-administration/ms-intune/custom-lockscreen.mdx
  website/docusaurus.config.ts
  website/redirects.ts
  website/sidebars.ts
  website/src/components/BrowserWindow/IframeWindow.tsx
  website/src/components/BrowserWindow/index.tsx
  website/src/components/ProjectCards/Projects.tsx
  website/src/components/ProjectCards/styles.module.css
  website/src/components/TeamProfileCards/index.tsx
  website/src/css/custom.css
  website/src/pages/learn/index.tsx
  website/src/pages/learn/styles.module.css
  website/src/pages/me/index.tsx
  website/src/pages/projects/_components/projectCards/index.tsx
  website/src/pages/projects/index.tsx
  website/src/pages/projects/styles.module.css
  website/src/pages/tests/_tests.mdx
  website/static/img/logo/Cloudflare_Logo.svg
  website/static/img/projects/download.png
  website/static/img/undraw_taken.svg
Labels: pr: internal

#402 docs: intial contribution
  website/src/components/TeamProfileCards/index.tsx
Labels: good first issue, pr: internal

#404 docs: update guides
  website/docs/system-administration/02-cli.mdx
Labels: documentation, pr: internal

#405 misc: update GitHub actions and some docs
  .github/workflows/build-and-deploy.yml
Labels: pr: internal
